name: Auto-label BUG from Project status

on:
  issues:
    types: [opened, edited]

jobs:
  add-bug-if-status:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      repository-projects: read
    steps:
      - name: Check project status for this issue
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          RESP=$(gh api graphql -f query='
          query($id:ID!){
            node(id:$id){
              ... on Issue {
                projectItems(first:10){
                  nodes{
                    fieldValueByName(name:"Status"){
                      ... on ProjectV2ItemFieldSingleSelectValue { name }
                    }
                  }
                }
              }
            }
          }' -F id="$ISSUE_ID")

          STATUS=$(jq -r '.data.node.projectItems.nodes[].fieldValueByName.name // empty' <<<"$RESP")
          echo "status=$STATUS" >> $GITHUB_OUTPUT

      - name: Add bug label
        if: ${{ steps.check.outputs.status == 'BUG REQUESTS' }}
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label bug
