name: Ticketing — Email depuis Issues

on:
  issues:
    types: [opened, edited, closed, reopened, labeled, unlabeled, assigned, unassigned]
  issue_comment:
    types: [created] # ajoute 'edited' si tu veux aussi sur édition

jobs:
  mail:
    runs-on: ubuntu-latest

    steps:
      # Version actuelle recommandée (v6, publiée en 2025)
      # https://github.com/dawidd6/action-send-mail
      # ------------------------------------------------

      # Envoi quand c’est un commentaire d’issue
      - name: Send email (issue_comment event)
        if: ${{ github.event_name == 'issue_comment' }}
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          secure: ${{ secrets.SMTP_PORT == '465' }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}

          from: "Ticket Bot <${{ secrets.SMTP_USERNAME }}>"
          to: ${{ secrets.TICKETS_TO }}
          reply_to: ${{ secrets.SMTP_USERNAME }}

          subject: "Coucou Océ: mail envoyé automatiquement à partir d'une issue #${{ github.event.issue.number }}"
          html_body: |
            **Commentateur:** @${{ github.actor }}
            **Issue:** #${{ github.event.issue.number }} – ${{ github.event.issue.title }}
            **URL:** ${{ github.event.comment.html_url }}

            ---

            ${{ github.event.comment.body }}
          convert_markdown: true
